name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Hello CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      EC2_HOST: 13.218.157.147
      EC2_USER: ubuntu

    steps:
    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MY_EC2_KEYS }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to Known Hosts
      run: |
        ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

    - name: SSH into EC2
      run: |
        ssh $EC2_USER@$EC2_HOST ,, 'EOF'
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker pull chikadev/jsapp:latest
            docker stop jsapp-container || true
            docker rm jsapp-container || true
            docker run -d --name jsapp-container -p 80:3000 chikadev/jsapp:latest
        EOF

    - name: Pull Docker Image and Run Container
      run: echo "Deployment completed successfully."
